version: "3.8"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - database

    # Database Server
    database:
        image: mariadb:10.4.28
        ports:
            - 3306:3306
        environment:
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mariadb

volumes:
    db-data: ~
